service:
    path: '/service'
    defaults: { _controller: 'vocento.service.controller:serviceAction' }
    requirements:
        methods: ['GET']

service.name:
    path: '/service/name'
    defaults: { _controller: 'vocento.service.controller:nameAction' }
    requirements:
        methods: ['GET']

service.versions.list:
    path: '/service/versions'
    defaults: { _controller: 'vocento.service.controller:versionsAction' }
    requirements:
        methods: ['GET']

service.versions.current:
    path: '/service/versions/current'
    defaults: { _controller: 'vocento.service.controller:currentVersionAction' }
    requirements:
        methods: ['GET']
