services:
    vocento.service.controller:
        class: Vocento\MicroserviceBundle\Controller\ServiceController
        public: true
        arguments:
            - '%microservice.name%'
            - '%microservice.code_version%'
            - '%microservice.versions.list%'
            - '%microservice.versions.current%'
