language: php

php:
  - 7.1
  - 7.4

cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/phpunit --coverage-text

notifications:
  email:
    - arquitectura@vocento.com
