language: php

php:
  - 5.6

cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/phpunit --coverage-text

notifications:
  email:
    - aferrandini@vocento.com
