language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install

script:
  - ./bin/phpunit --coverage-text

notifications:
  email:
    - aferrandini@vocento.com
