service.name:
    path: '/service/name.{_format}'
    defaults: { _controller: 'vocento.microservice.controller:nameAction' }
    requirements:
        _format: 'json'

service.versions.list:
    path: '/service/versions.{_format}'
    defaults: { _controller: 'vocento.microservice.controller:versionsAction' }
    requirements:
        _format: 'json'

service.versions.current:
    path: '/service/versions/current.{_format}'
    defaults: { _controller: 'vocento.microservice.controller:currentVersionAction' }
    requirements:
        _format: 'json'
